package gitbot

import (
	"encoding/json"
	"testing"
)

func TestPayloadPullRequest(t *testing.T) {
	payload := `{
  "action": "opened",
  "number": 34,
  "pull_request": {
    "url": "https://api.github.com/repos/aarondl/ultimateq/pulls/34",
    "id": 31366769,
    "html_url": "https://github.com/aarondl/ultimateq/pull/34",
    "diff_url": "https://github.com/aarondl/ultimateq/pull/34.diff",
    "patch_url": "https://github.com/aarondl/ultimateq/pull/34.patch",
    "issue_url": "https://api.github.com/repos/aarondl/ultimateq/issues/34",
    "number": 34,
    "state": "open",
    "locked": false,
    "title": "Add Dockerfile",
    "user": {
      "login": "monokrome",
      "id": 242997,
      "avatar_url": "https://avatars.githubusercontent.com/u/242997?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/monokrome",
      "html_url": "https://github.com/monokrome",
      "followers_url": "https://api.github.com/users/monokrome/followers",
      "following_url": "https://api.github.com/users/monokrome/following{/other_user}",
      "gists_url": "https://api.github.com/users/monokrome/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/monokrome/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/monokrome/subscriptions",
      "organizations_url": "https://api.github.com/users/monokrome/orgs",
      "repos_url": "https://api.github.com/users/monokrome/repos",
      "events_url": "https://api.github.com/users/monokrome/events{/privacy}",
      "received_events_url": "https://api.github.com/users/monokrome/received_events",
      "type": "User",
      "site_admin": false
    },
    "body": "",
    "created_at": "2015-03-17T18:59:02Z",
    "updated_at": "2015-03-17T18:59:02Z",
    "closed_at": null,
    "merged_at": null,
    "merge_commit_sha": null,
    "assignee": null,
    "milestone": null,
    "commits_url": "https://api.github.com/repos/aarondl/ultimateq/pulls/34/commits",
    "review_comments_url": "https://api.github.com/repos/aarondl/ultimateq/pulls/34/comments",
    "review_comment_url": "https://api.github.com/repos/aarondl/ultimateq/pulls/comments{/number}",
    "comments_url": "https://api.github.com/repos/aarondl/ultimateq/issues/34/comments",
    "statuses_url": "https://api.github.com/repos/aarondl/ultimateq/statuses/1674fd7663e1ced237b5fbecdcf34e9f642601d6",
    "head": {
      "label": "monokrome:master",
      "ref": "master",
      "sha": "1674fd7663e1ced237b5fbecdcf34e9f642601d6",
      "user": {
        "login": "monokrome",
        "id": 242997,
        "avatar_url": "https://avatars.githubusercontent.com/u/242997?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/monokrome",
        "html_url": "https://github.com/monokrome",
        "followers_url": "https://api.github.com/users/monokrome/followers",
        "following_url": "https://api.github.com/users/monokrome/following{/other_user}",
        "gists_url": "https://api.github.com/users/monokrome/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/monokrome/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/monokrome/subscriptions",
        "organizations_url": "https://api.github.com/users/monokrome/orgs",
        "repos_url": "https://api.github.com/users/monokrome/repos",
        "events_url": "https://api.github.com/users/monokrome/events{/privacy}",
        "received_events_url": "https://api.github.com/users/monokrome/received_events",
        "type": "User",
        "site_admin": false
      },
      "repo": {
        "id": 32413448,
        "name": "ultimateq",
        "full_name": "monokrome/ultimateq",
        "owner": {
          "login": "monokrome",
          "id": 242997,
          "avatar_url": "https://avatars.githubusercontent.com/u/242997?v=3",
          "gravatar_id": "",
          "url": "https://api.github.com/users/monokrome",
          "html_url": "https://github.com/monokrome",
          "followers_url": "https://api.github.com/users/monokrome/followers",
          "following_url": "https://api.github.com/users/monokrome/following{/other_user}",
          "gists_url": "https://api.github.com/users/monokrome/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/monokrome/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/monokrome/subscriptions",
          "organizations_url": "https://api.github.com/users/monokrome/orgs",
          "repos_url": "https://api.github.com/users/monokrome/repos",
          "events_url": "https://api.github.com/users/monokrome/events{/privacy}",
          "received_events_url": "https://api.github.com/users/monokrome/received_events",
          "type": "User",
          "site_admin": false
        },
        "private": false,
        "html_url": "https://github.com/monokrome/ultimateq",
        "description": "An irc bot written in Go.",
        "fork": true,
        "url": "https://api.github.com/repos/monokrome/ultimateq",
        "forks_url": "https://api.github.com/repos/monokrome/ultimateq/forks",
        "keys_url": "https://api.github.com/repos/monokrome/ultimateq/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/monokrome/ultimateq/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/monokrome/ultimateq/teams",
        "hooks_url": "https://api.github.com/repos/monokrome/ultimateq/hooks",
        "issue_events_url": "https://api.github.com/repos/monokrome/ultimateq/issues/events{/number}",
        "events_url": "https://api.github.com/repos/monokrome/ultimateq/events",
        "assignees_url": "https://api.github.com/repos/monokrome/ultimateq/assignees{/user}",
        "branches_url": "https://api.github.com/repos/monokrome/ultimateq/branches{/branch}",
        "tags_url": "https://api.github.com/repos/monokrome/ultimateq/tags",
        "blobs_url": "https://api.github.com/repos/monokrome/ultimateq/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/monokrome/ultimateq/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/monokrome/ultimateq/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/monokrome/ultimateq/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/monokrome/ultimateq/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/monokrome/ultimateq/languages",
        "stargazers_url": "https://api.github.com/repos/monokrome/ultimateq/stargazers",
        "contributors_url": "https://api.github.com/repos/monokrome/ultimateq/contributors",
        "subscribers_url": "https://api.github.com/repos/monokrome/ultimateq/subscribers",
        "subscription_url": "https://api.github.com/repos/monokrome/ultimateq/subscription",
        "commits_url": "https://api.github.com/repos/monokrome/ultimateq/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/monokrome/ultimateq/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/monokrome/ultimateq/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/monokrome/ultimateq/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/monokrome/ultimateq/contents/{+path}",
        "compare_url": "https://api.github.com/repos/monokrome/ultimateq/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/monokrome/ultimateq/merges",
        "archive_url": "https://api.github.com/repos/monokrome/ultimateq/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/monokrome/ultimateq/downloads",
        "issues_url": "https://api.github.com/repos/monokrome/ultimateq/issues{/number}",
        "pulls_url": "https://api.github.com/repos/monokrome/ultimateq/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/monokrome/ultimateq/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/monokrome/ultimateq/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/monokrome/ultimateq/labels{/name}",
        "releases_url": "https://api.github.com/repos/monokrome/ultimateq/releases{/id}",
        "created_at": "2015-03-17T18:51:01Z",
        "updated_at": "2015-03-17T18:58:43Z",
        "pushed_at": "2015-03-17T18:58:43Z",
        "git_url": "git://github.com/monokrome/ultimateq.git",
        "ssh_url": "git@github.com:monokrome/ultimateq.git",
        "clone_url": "https://github.com/monokrome/ultimateq.git",
        "svn_url": "https://github.com/monokrome/ultimateq",
        "homepage": null,
        "size": 1797,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "Go",
        "has_issues": false,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "open_issues_count": 0,
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master"
      }
    },
    "base": {
      "label": "aarondl:master",
      "ref": "master",
      "sha": "7840f56b25646255bd0f02285c3f1e4619d11554",
      "user": {
        "login": "aarondl",
        "id": 699706,
        "avatar_url": "https://avatars.githubusercontent.com/u/699706?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/aarondl",
        "html_url": "https://github.com/aarondl",
        "followers_url": "https://api.github.com/users/aarondl/followers",
        "following_url": "https://api.github.com/users/aarondl/following{/other_user}",
        "gists_url": "https://api.github.com/users/aarondl/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/aarondl/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/aarondl/subscriptions",
        "organizations_url": "https://api.github.com/users/aarondl/orgs",
        "repos_url": "https://api.github.com/users/aarondl/repos",
        "events_url": "https://api.github.com/users/aarondl/events{/privacy}",
        "received_events_url": "https://api.github.com/users/aarondl/received_events",
        "type": "User",
        "site_admin": false
      },
      "repo": {
        "id": 9417576,
        "name": "ultimateq",
        "full_name": "aarondl/ultimateq",
        "owner": {
          "login": "aarondl",
          "id": 699706,
          "avatar_url": "https://avatars.githubusercontent.com/u/699706?v=3",
          "gravatar_id": "",
          "url": "https://api.github.com/users/aarondl",
          "html_url": "https://github.com/aarondl",
          "followers_url": "https://api.github.com/users/aarondl/followers",
          "following_url": "https://api.github.com/users/aarondl/following{/other_user}",
          "gists_url": "https://api.github.com/users/aarondl/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/aarondl/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/aarondl/subscriptions",
          "organizations_url": "https://api.github.com/users/aarondl/orgs",
          "repos_url": "https://api.github.com/users/aarondl/repos",
          "events_url": "https://api.github.com/users/aarondl/events{/privacy}",
          "received_events_url": "https://api.github.com/users/aarondl/received_events",
          "type": "User",
          "site_admin": false
        },
        "private": false,
        "html_url": "https://github.com/aarondl/ultimateq",
        "description": "An irc bot written in Go.",
        "fork": false,
        "url": "https://api.github.com/repos/aarondl/ultimateq",
        "forks_url": "https://api.github.com/repos/aarondl/ultimateq/forks",
        "keys_url": "https://api.github.com/repos/aarondl/ultimateq/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/aarondl/ultimateq/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/aarondl/ultimateq/teams",
        "hooks_url": "https://api.github.com/repos/aarondl/ultimateq/hooks",
        "issue_events_url": "https://api.github.com/repos/aarondl/ultimateq/issues/events{/number}",
        "events_url": "https://api.github.com/repos/aarondl/ultimateq/events",
        "assignees_url": "https://api.github.com/repos/aarondl/ultimateq/assignees{/user}",
        "branches_url": "https://api.github.com/repos/aarondl/ultimateq/branches{/branch}",
        "tags_url": "https://api.github.com/repos/aarondl/ultimateq/tags",
        "blobs_url": "https://api.github.com/repos/aarondl/ultimateq/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/aarondl/ultimateq/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/aarondl/ultimateq/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/aarondl/ultimateq/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/aarondl/ultimateq/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/aarondl/ultimateq/languages",
        "stargazers_url": "https://api.github.com/repos/aarondl/ultimateq/stargazers",
        "contributors_url": "https://api.github.com/repos/aarondl/ultimateq/contributors",
        "subscribers_url": "https://api.github.com/repos/aarondl/ultimateq/subscribers",
        "subscription_url": "https://api.github.com/repos/aarondl/ultimateq/subscription",
        "commits_url": "https://api.github.com/repos/aarondl/ultimateq/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/aarondl/ultimateq/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/aarondl/ultimateq/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/aarondl/ultimateq/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/aarondl/ultimateq/contents/{+path}",
        "compare_url": "https://api.github.com/repos/aarondl/ultimateq/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/aarondl/ultimateq/merges",
        "archive_url": "https://api.github.com/repos/aarondl/ultimateq/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/aarondl/ultimateq/downloads",
        "issues_url": "https://api.github.com/repos/aarondl/ultimateq/issues{/number}",
        "pulls_url": "https://api.github.com/repos/aarondl/ultimateq/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/aarondl/ultimateq/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/aarondl/ultimateq/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/aarondl/ultimateq/labels{/name}",
        "releases_url": "https://api.github.com/repos/aarondl/ultimateq/releases{/id}",
        "created_at": "2013-04-13T17:50:39Z",
        "updated_at": "2015-01-07T13:47:16Z",
        "pushed_at": "2015-03-08T07:45:00Z",
        "git_url": "git://github.com/aarondl/ultimateq.git",
        "ssh_url": "git@github.com:aarondl/ultimateq.git",
        "clone_url": "https://github.com/aarondl/ultimateq.git",
        "svn_url": "https://github.com/aarondl/ultimateq",
        "homepage": null,
        "size": 1797,
        "stargazers_count": 9,
        "watchers_count": 9,
        "language": "Go",
        "has_issues": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 4,
        "mirror_url": null,
        "open_issues_count": 6,
        "forks": 4,
        "open_issues": 6,
        "watchers": 9,
        "default_branch": "master"
      }
    },
    "_links": {
      "self": {
        "href": "https://api.github.com/repos/aarondl/ultimateq/pulls/34"
      },
      "html": {
        "href": "https://github.com/aarondl/ultimateq/pull/34"
      },
      "issue": {
        "href": "https://api.github.com/repos/aarondl/ultimateq/issues/34"
      },
      "comments": {
        "href": "https://api.github.com/repos/aarondl/ultimateq/issues/34/comments"
      },
      "review_comments": {
        "href": "https://api.github.com/repos/aarondl/ultimateq/pulls/34/comments"
      },
      "review_comment": {
        "href": "https://api.github.com/repos/aarondl/ultimateq/pulls/comments{/number}"
      },
      "commits": {
        "href": "https://api.github.com/repos/aarondl/ultimateq/pulls/34/commits"
      },
      "statuses": {
        "href": "https://api.github.com/repos/aarondl/ultimateq/statuses/1674fd7663e1ced237b5fbecdcf34e9f642601d6"
      }
    },
    "merged": false,
    "mergeable": null,
    "mergeable_state": "unknown",
    "merged_by": null,
    "comments": 0,
    "review_comments": 0,
    "commits": 1,
    "additions": 1,
    "deletions": 0,
    "changed_files": 1
  },
  "repository": {
    "id": 9417576,
    "name": "ultimateq",
    "full_name": "aarondl/ultimateq",
    "owner": {
      "login": "aarondl",
      "id": 699706,
      "avatar_url": "https://avatars.githubusercontent.com/u/699706?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/aarondl",
      "html_url": "https://github.com/aarondl",
      "followers_url": "https://api.github.com/users/aarondl/followers",
      "following_url": "https://api.github.com/users/aarondl/following{/other_user}",
      "gists_url": "https://api.github.com/users/aarondl/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/aarondl/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/aarondl/subscriptions",
      "organizations_url": "https://api.github.com/users/aarondl/orgs",
      "repos_url": "https://api.github.com/users/aarondl/repos",
      "events_url": "https://api.github.com/users/aarondl/events{/privacy}",
      "received_events_url": "https://api.github.com/users/aarondl/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/aarondl/ultimateq",
    "description": "An irc bot written in Go.",
    "fork": false,
    "url": "https://api.github.com/repos/aarondl/ultimateq",
    "forks_url": "https://api.github.com/repos/aarondl/ultimateq/forks",
    "keys_url": "https://api.github.com/repos/aarondl/ultimateq/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/aarondl/ultimateq/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/aarondl/ultimateq/teams",
    "hooks_url": "https://api.github.com/repos/aarondl/ultimateq/hooks",
    "issue_events_url": "https://api.github.com/repos/aarondl/ultimateq/issues/events{/number}",
    "events_url": "https://api.github.com/repos/aarondl/ultimateq/events",
    "assignees_url": "https://api.github.com/repos/aarondl/ultimateq/assignees{/user}",
    "branches_url": "https://api.github.com/repos/aarondl/ultimateq/branches{/branch}",
    "tags_url": "https://api.github.com/repos/aarondl/ultimateq/tags",
    "blobs_url": "https://api.github.com/repos/aarondl/ultimateq/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/aarondl/ultimateq/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/aarondl/ultimateq/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/aarondl/ultimateq/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/aarondl/ultimateq/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/aarondl/ultimateq/languages",
    "stargazers_url": "https://api.github.com/repos/aarondl/ultimateq/stargazers",
    "contributors_url": "https://api.github.com/repos/aarondl/ultimateq/contributors",
    "subscribers_url": "https://api.github.com/repos/aarondl/ultimateq/subscribers",
    "subscription_url": "https://api.github.com/repos/aarondl/ultimateq/subscription",
    "commits_url": "https://api.github.com/repos/aarondl/ultimateq/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/aarondl/ultimateq/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/aarondl/ultimateq/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/aarondl/ultimateq/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/aarondl/ultimateq/contents/{+path}",
    "compare_url": "https://api.github.com/repos/aarondl/ultimateq/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/aarondl/ultimateq/merges",
    "archive_url": "https://api.github.com/repos/aarondl/ultimateq/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/aarondl/ultimateq/downloads",
    "issues_url": "https://api.github.com/repos/aarondl/ultimateq/issues{/number}",
    "pulls_url": "https://api.github.com/repos/aarondl/ultimateq/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/aarondl/ultimateq/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/aarondl/ultimateq/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/aarondl/ultimateq/labels{/name}",
    "releases_url": "https://api.github.com/repos/aarondl/ultimateq/releases{/id}",
    "created_at": "2013-04-13T17:50:39Z",
    "updated_at": "2015-01-07T13:47:16Z",
    "pushed_at": "2015-03-08T07:45:00Z",
    "git_url": "git://github.com/aarondl/ultimateq.git",
    "ssh_url": "git@github.com:aarondl/ultimateq.git",
    "clone_url": "https://github.com/aarondl/ultimateq.git",
    "svn_url": "https://github.com/aarondl/ultimateq",
    "homepage": null,
    "size": 1797,
    "stargazers_count": 9,
    "watchers_count": 9,
    "language": "Go",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 4,
    "mirror_url": null,
    "open_issues_count": 6,
    "forks": 4,
    "open_issues": 6,
    "watchers": 9,
    "default_branch": "master"
  },
  "sender": {
    "login": "monokrome",
    "id": 242997,
    "avatar_url": "https://avatars.githubusercontent.com/u/242997?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/monokrome",
    "html_url": "https://github.com/monokrome",
    "followers_url": "https://api.github.com/users/monokrome/followers",
    "following_url": "https://api.github.com/users/monokrome/following{/other_user}",
    "gists_url": "https://api.github.com/users/monokrome/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/monokrome/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/monokrome/subscriptions",
    "organizations_url": "https://api.github.com/users/monokrome/orgs",
    "repos_url": "https://api.github.com/users/monokrome/repos",
    "events_url": "https://api.github.com/users/monokrome/events{/privacy}",
    "received_events_url": "https://api.github.com/users/monokrome/received_events",
    "type": "User",
    "site_admin": false
  }
}`

	var p PayloadPullRequest
	if err := json.Unmarshal([]byte(payload), &p); err != nil {
		t.Error(err)
	}

	if str := p.String(); str != "[aarondl/ultimateq] monokrome opened pull request #34 Add Dockerfile (https://github.com/aarondl/ultimateq/pull/34)" {
		t.Error("String is wrong:", str)
	}
}
